// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj4rTN_0f4NWxKGqr1YZjsP25xkwd0Fi8',
    appId: '1:662940128104:web:d0dbd69c09db4b8b90bcdd',
    messagingSenderId: '662940128104',
    projectId: 'captain-fc0f1',
    authDomain: 'captain-fc0f1.firebaseapp.com',
    storageBucket: 'captain-fc0f1.firebasestorage.app',
    measurementId: 'G-LW6D677RFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWWUt_XhEnWl5pG8XsnuQKOHZUg8H6aO4',
    appId: '1:662940128104:android:a1422fa01357c8da90bcdd',
    messagingSenderId: '662940128104',
    projectId: 'captain-fc0f1',
    storageBucket: 'captain-fc0f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI9GqXrCg0STfQj6EHlq6KtaqWC5OpYBc',
    appId: '1:662940128104:ios:5b9c2128e1e1467290bcdd',
    messagingSenderId: '662940128104',
    projectId: 'captain-fc0f1',
    storageBucket: 'captain-fc0f1.firebasestorage.app',
    iosBundleId: 'com.captainmasala.captainMasala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI9GqXrCg0STfQj6EHlq6KtaqWC5OpYBc',
    appId: '1:662940128104:ios:5b9c2128e1e1467290bcdd',
    messagingSenderId: '662940128104',
    projectId: 'captain-fc0f1',
    storageBucket: 'captain-fc0f1.firebasestorage.app',
    iosBundleId: 'com.captainmasala.captainMasala',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj4rTN_0f4NWxKGqr1YZjsP25xkwd0Fi8',
    appId: '1:662940128104:web:9e1c7f94951e161590bcdd',
    messagingSenderId: '662940128104',
    projectId: 'captain-fc0f1',
    authDomain: 'captain-fc0f1.firebaseapp.com',
    storageBucket: 'captain-fc0f1.firebasestorage.app',
    measurementId: 'G-QMWMBTVJTL',
  );
}
